language: node_js
required: sudo
node_js:
- '9'
services:
- docker
- ntp
- xvfb
addons:
  chrome: stable
  apt:
    sources:
    - google-chrome
    packages:
    - xvfb
    - libgif-dev
    - google-chrome-stable
script:
- "./scripts/authelia-scripts travis"
after_success:
- "./scripts/authelia-scripts docker publish"

deploy:
  provider: npm
  email: clement.michaud34@gmail.com
  skip_cleanup: true
  api_key:
    secure: GozHZ8/nk56lXzV9N+ywzgfUr89Qths9BDrD5vMR8FtvzH6KMLClgQHv9I/eLkmvCrhRkamyG9u7hgKaBrwQXewNAtJqrPKW/mmY+90NxFWRljsVqnvc0YWwA9FpgniPvbN/AY4qpiELp48lOLIB1X9WgTI4LUJ0j8QoadUUiK9mzZmVo6RXkY2OZfji8J4vxoOdyRmhN+sRcncYztR+H39xUatGLN50UOieXCmsN8fp/gQUVgF3HwebWEVocZ6tbjyVUkpInYEEAeA4DheUw11S0xt9nxNweM9XYG2LUqYSr8JIhbtEUmjyC8tQC+MqitHQBf91xctZnenmjCmpmrlAc6JLFkN5wYOCqpz4ZlxgDwKznqnldqgLfhCtFq8kp032KQr3XpH0nur8ccRqXNGKn32CmijprgCRYanXn7R84XOA/TleGUFWDqO+tPZjBQ1ob8y+SQpMhK+AbTnFWccXUb7PlCJ5UFAyejyrrmn2fDlp3ofqunk2siv5e3fn20uVLUk6assaybclFGlSy3xDTqOApTXvSAIaUfMtV2VnNH9FwhlhmPh4DgG2ph/nInW9pQh3ku5zaUcaPWaMYF5Pk3S3mwvCWr9eGAX+NDyJlLMIAq3nZr+v0450J3VEOs23GTdIAJnJrDy5L0TVdWEcP4cLAv32q1OkQJD947Y=
  on:
    tags: true
    repo: clems4ever/authelia
notifications:
  email:
    recipients:
    - clement.michaud34@gmail.com
    on_success: change
    on_failure: always
